BEGIN;

INSERT INTO public.cuisine_types (name, description)
VALUES
('American', 'Burgers, hot dogs, and fries, embodying classic American fare.'),
('Mexican', 'Tacos, burritos, and quesadillas showcasing rich flavors.'),
('BBQ', 'Brisket, pulled pork, ribs, all slow-cooked with smoky flavors.'),
('Italian', 'Pizza, pasta, and gelato representing Italy''s culinary heritage.'),
('Asian Fusion', 'Mix of different Asian culinary traditions for a unique taste.'),
('Korean', 'Korean BBQ, kimchi, and bulgogi with bold flavors.'),
('Chinese', 'Dumplings, noodles, and fried rice from various Chinese regions.'),
('Japanese', 'Sushi, ramen, and takoyaki, highlighting Japanese cuisine''s diversity.'),
('Thai', 'Pad Thai, curry, and satay with aromatic herbs and spices.'),
('Indian', 'Curries, naan, and samosas with a blend of spices.'),
('Vietnamese', 'Banh mi, pho, and spring rolls, known for fresh flavors.'),
('Greek', 'Gyros, souvlaki, and baklava, reflecting Mediterranean tastes.'),
('Mediterranean', 'Falafel, hummus, and kebabs from Mediterranean countries.'),
('Southern', 'Fried chicken, biscuits, and grits from the American South.'),
('Tex-Mex', 'Enchiladas, fajitas, and nachos with a Texas twist.'),
('Hawaiian', 'Poke, spam musubi, and shaved ice from the Hawaiian islands.'),
('Caribbean', 'Jerk chicken, plantains, and rice and peas with tropical flair.'),
('Filipino', 'Adobo, lumpia, and lechon, showcasing Filipino culinary art.'),
('Cuban', 'Cuban sandwiches, empanadas, and croquetas with Cuban zest.'),
('Brazilian', 'Churrasco, coxinha, and feijoada from Brazil''s rich food culture.'),
('Gourmet Grilled Cheese', 'Innovative variations on the classic grilled cheese sandwich.'),
('Gourmet Burgers', 'High-quality, unique burger offerings with gourmet toppings.'),
('Seafood', 'Lobster rolls, fish tacos, and shrimp dishes from the sea.'),
('Vegan/Vegetarian', 'Plant-based options like tofu bowls and veggie burgers.'),
('Desserts', 'Specialty items like ice cream, cupcakes, and churros.'),
('Coffee and Espresso', 'Specialty coffee drinks and espresso-based beverages.'),
('French', 'Crepes, baguettes, and macarons with French finesse.'),
('German', 'Bratwurst, pretzels, and schnitzel from German traditions.'),
('Middle Eastern', 'Shawarma, tabbouleh, and baklava from the Middle East.'),
('Argentinian', 'Empanadas, choripan, and asado with Argentinean flair.'),
('Peruvian', 'Ceviche, lomo saltado, and anticuchos from Peru.'),
('Spanish', 'Paella, tapas, and churros representing Spanish cuisine.'),
('Soul Food', 'Collard greens, mac and cheese, and meatloaf from African American cuisine.'),
('Ethiopian', 'Injera, doro wat, and vegetarian combos with unique flavors.'),
('Lebanese', 'Shawarma, tabbouleh, and fattoush from Lebanon.'),
('Fusion', 'Mixing cuisines like Korean-Mexican tacos for creative dishes.'),
('Cajun/Creole', 'Jambalaya, gumbo, and po'' boys from Louisiana.'),
('Turkish', 'Doner kebab, baklava, and simit from Turkey.'),
('Polish', 'Pierogi, kielbasa, and bigos representing Polish cuisine.'),
('Southeast Asian', 'Dishes from Malaysia, Indonesia, or Singapore.'),
('Irish', 'Shepherd''s pie, bangers and mash, and soda bread.'),
('Scandinavian', 'Meatballs, open-faced sandwiches, and pastries from Nordic countries.'),
('African', 'Jollof rice, suya, and injera from various African countries.'),
('Latin American', 'Arepas, pupusas, and tamales from across Latin America.'),
('Portuguese', 'Pastel de nata, caldo verde, and grilled sardines from Portugal.'),
('Jamaican', 'Jerk, patties, and ackee and saltfish from Jamaica.'),
('New England', 'Clam chowder, lobster rolls, and whoopie pies.'),
('Pacific Northwest', 'Salmon, Dungeness crab, and craft beers from the PNW.'),
('Southwest', 'Green chile, sopapillas, and carne asada from the Southwest.'),
('Farm-to-Table', 'Locally sourced, seasonal dishes focusing on freshness.'),
('Sushi', 'Raw fish, rice, and seaweed rolled into culinary art.'),
('Tacos', 'Various fillings wrapped in soft or hard shells.'),
('Pizza', 'Flatbread with toppings like cheese, veggies, and meats.'),
('Sandwiches', 'Bread with a variety of fillings for convenience and taste.'),
('Burgers', 'Beef patty or alternative served on a bun with toppings.'),
('Hot Dogs', 'Sausage in a bun, customizable with numerous condiments.'),
('Wraps', 'Food wrapped in flatbread for an easy-to-eat meal.'),
('Salads', 'Healthy mix of greens and other ingredients, often customizable.'),
('Smoothies', 'Blended fruits and vegetables for a refreshing drink.'),
('Juice', 'Freshly squeezed or cold-pressed fruit or vegetable juice.'),
('Boba Tea', 'Tea with milk and tapioca pearls, a Taiwanese specialty.'),
('Donuts', 'Fried dough, often with sweet glazes or fillings.'),
('Cupcakes', 'Small cakes designed for individual servings.'),
('Ice Cream', 'Frozen dessert made from milk, cream, and flavors.'),
('Shaved Ice', 'Flavored syrups over finely shaved ice for a cool treat.'),
('Funnel Cakes', 'Fried batter with powdered sugar, a fairground favorite.'),
('Churros', 'Fried dough pastry sprinkled with sugar or cinnamon.'),
('Waffles', 'Batter cooked between plates, creating a grid pattern.'),
('Mac ''n Cheese', 'Pasta mixed with cheese sauce, sometimes with added toppings.'),
('Fried Chicken', 'Battered and deep-fried chicken, often crispy and juicy.'),
('Ramen', 'Japanese noodle soup with various flavors and toppings.'),
('Noodles', 'Various types of noodles from different culinary traditions.'),
('Samosas', 'Fried or baked pastry with savory fillings, popular in India.'),
('Empanadas', 'Stuffed pastries from Latin America, baked or fried.'),
('Pretzels', 'Baked dough with a distinctive shape, often salted.'),
('Pierogi', 'Dumplings filled with various ingredients, from Poland.'),
('Poke', 'Diced raw fish with seasonings, a Hawaiian dish.'),
('Dim Sum', 'Small bite-sized portions of food served in steamer baskets.'),
('Paella', 'Spanish rice dish with meat, seafood, or vegetables.'),
('Falafel', 'Deep-fried balls made from chickpeas or fava beans.'),
('Gyoza', 'Japanese dumplings, often filled with meat and vegetables.'),
('Curry', 'Spicy dish with a sauce, originating from South Asia.'),
('Pho', 'Vietnamese soup with broth, rice noodles, herbs, and meat.'),
('Banh Mi', 'Vietnamese sandwich with crusty bread and various fillings.'),
('Tostadas', 'Crunchy tortilla base with toppings like beans, meat, and salsa.'),
('Ceviche', 'Marinated raw fish or seafood in citrus juices.'),
('Jerk', 'Spicy marinated and grilled meat, from Jamaica.'),
('Pupusas', 'Thick corn tortillas stuffed with cheese, meat, or beans, from El Salvador.'),
('Arepas', 'Venezuelan and Colombian cornmeal cakes, often split and stuffed.'),
('Tamales', 'Steamed masa dough with fillings, wrapped in corn husks.'),
('Kebabs', 'Meat or vegetables grilled on skewers from Middle Eastern cuisine.'),
('Schnitzel', 'Breaded and fried meat cutlet, popular in German-speaking countries.'),
('Kolaches', 'Sweet or savory pastries from Czech and Texas traditions.'),
('Fish and Chips', 'Battered fish and deep-fried chips, a British classic.'),
('Crepes', 'Thin pancakes, can be sweet or savory.'),
('Baklava', 'Sweet pastry made of layers of filo filled with nuts and syrup.'),
('Corn Dogs', 'Hot dogs coated in cornmeal batter and deep-fried.'),
('Gourmet Fries', 'Fries with creative or gourmet toppings and seasonings.'),
('Poutine', 'Canadian dish of fries topped with cheese curds and gravy.');

COMMIT;
